name: Preview Build

on:
  pull_request:
    branches: [ gatsby ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: configure node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: install deps
      run: yarn install

    - name: build gatsby
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: copy preview
      run: aws s3 cp --recursive public s3://my-s3-prod-website-bucket/${GIHUB_SHA}

    

